# KNN ALGORITHM IMPLEMENTATION USING SCRATCH(HERE USE HEART DATA SET)

In [8]:
import pandas as pd
import numpy as np

In [9]:
# DATASET LOADING

heart = pd.read_csv(r"C:\Users\UNICORN\Desktop\Datasets\heart.csv")

In [10]:
heart.shape

(303, 14)

In [11]:
heart.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [12]:
data_heart=heart[['age','sex','cp','trestbps','chol','fbs','restecg','thalach','exang','oldpeak','slope','ca','thal']]
data_heart.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  
0   0     1  
1   0     2  
2   0     2  
3   0     2  
4   0     2

In [13]:
result_heart=heart['target']

In [14]:
x=np.array(data_heart)
y=np.array(result_heart)

In [16]:
x

array([[63.,  1.,  3., ...,  0.,  0.,  1.],
       [37.,  1.,  2., ...,  0.,  0.,  2.],
       [41.,  0.,  1., ...,  2.,  0.,  2.],
       ...,
       [68.,  1.,  0., ...,  1.,  2.,  3.],
       [57.,  1.,  0., ...,  1.,  1.,  3.],
       [57.,  0.,  1., ...,  1.,  1.,  2.]])

In [17]:
# SCALLING THE DATA USING BETWEEN 0-1

transpose_x= np.transpose(x)
tr_x_row, tr_x_col = transpose_x.shape
for i in range(tr_x_row):
    max_val= np.max(transpose_x[i])
    min_val=np.min(transpose_x[i])
    for j in range(transpose_x[i].shape[0]):
        transpose_x[i,j]= (transpose_x[i,j]-min_val)/(max_val-min_val)
x=np.transpose(transpose_x)
print(x)

[[0.70833333 1.         1.         ... 0.         0.         0.33333333]
 [0.16666667 1.         0.66666667 ... 0.         0.         0.66666667]
 [0.25       0.         0.33333333 ... 1.         0.         0.66666667]
 ...
 [0.8125     1.         0.         ... 0.5        0.5        1.        ]
 [0.58333333 1.         0.         ... 0.5        0.25       1.        ]
 [0.58333333 0.         0.33333333 ... 0.5        0.25       0.66666667]]


In [33]:
# SPLITTING DATASET INTO TRAIN AND TEST

In [29]:
import random
row, col= x.shape
row_count_for_train = round(row*0.8)
train_rows=[]
test_rows = []
while len(train_rows)<row_count_for_train:
    random_num = random.randint(0,row-1)
    if random_num not in train_rows :
        train_rows.append(random_num)
        
        
for i in range(row):
    if i not in train_rows:
        test_rows.append(i)
random.shuffle(test_rows)

x_train= x[train_rows,]
x_test = y[train_rows,]

y_train = x[test_rows,]
y_test = y[test_rows,]

In [2]:
# FILL MODEL AND PREDICT

In [35]:
import math
def classify(l):
    max_time_occured = max(set(l), key = l.count)
    return max_time_occured


def predict(dist, x_train,x_test, k):
    sorted_dist = dist.copy()
    sorted_dist.sort()
    possible_prediction_list=[]
    
    for i in range(k):
        index = dist.index(sorted_dist[i])
        possible_prediction_list.append(x_test[index])
    final_predicted_value = classify(possible_prediction_list)
    return final_predicted_value

def fit_and_predict(x_train,x_test,y_train, k):
    y_pred=[]
    for this_test_row in range(len(y_train)):
        dist=[]
        for i in range(x_train.shape[0]):
            total=0
            for j in range(x_train.shape[1]):
                total+=(x_train[i,j] - y_train[this_test_row,j])**2
            dist.append(math.sqrt(total))
        predicted_value = predict(dist,x_train,x_test,k)
        y_pred.append(predicted_value)
    y_pred = np.array(y_pred)
    return y_pred

In [ ]:
#  See result for 


from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

k_value = input("Enter the values of k : ").split(',')
lower=k_value[0]
if len(k_value)==1:
    upper= k_value[0]
else:
    upper = k_value[1]
lower,upper= int(lower), int(upper)


for k in range(lower,upper+1):
    y_predicted = fit_and_predict(x_train,x_test,y_train, k)
    matrix = confusion_matrix(y_test,y_predicted)
    diagonal_sum=0
    total_sum=0
    
    for i in range(matrix.shape[0]):
        for j in range(matrix.shape[1]):
            if i==j:
                diagonal_sum+=matrix[i,j]
            total_sum+=matrix[i][j]
            
            
    print(f"\nValue of k = {k}  \n Accuracy = {(diagonal_sum/total_sum)*100}%")
    print(f"\nConfusion Matrix = \n{matrix}\n\n")
    print("Classification Report :- \n")
    print(f"{classification_report(y_test, y_predicted)}")
    print("\n\n\n")